TEMP_MSG1:
    stopTempMsg(1)
    return
TEMP_MSG2:
    stopTempMsg(2)
    return
TEMP_MSG3:
    stopTempMsg(3)
    return
TEMP_MSG4:
    stopTempMsg(4)
    return
TEMP_MSG5:
    stopTempMsg(5)
    return
TEMP_MSG6:
    stopTempMsg(6)
    return
TEMP_MSG7:
    stopTempMsg(7)
    return
TEMP_MSG8:
    stopTempMsg(8)
    return
TEMP_MSG9:
    stopTempMsg(9)
    return
TEMP_MSG10:
    stopTempMsg(10)
    return
TEMP_MSG11:
    stopTempMsg(11)
    return
TEMP_MSG12:
    stopTempMsg(12)
    return
TEMP_MSG13:
    stopTempMsg(13)
    return
TEMP_MSG14:
    stopTempMsg(14)
    return
TEMP_MSG15:
    stopTempMsg(15)
    return
TEMP_MSG16:
    stopTempMsg(16)
    return
TEMP_MSG17:
    stopTempMsg(17)
    return
TEMP_MSG18:
    stopTempMsg(18)
    return
TEMP_MSG19:
    stopTempMsg(19)
    return
TEMP_MSG20:
    stopTempMsg(20)
    return